### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by utkarsh-nan** [MartinBeckUT/BDSFinalProject#1]
---------------------------------------------------------------------------

ZeroDivisionError                         Traceback (most recent call last)

<ipython-input-9-b391941204c4> in <module>
     10            ['ProductRelated', 'ProductRelated_Duration']]    
     11 
---> 12 X['AvgAdministrative'] = X.apply(lambda x: AvgMinutes(Count = x['Administrative'], Duration = x['Administrative_Duration']), axis = 1)
     13 

~/PycharmProjects/MLProject/venv/lib/python3.7/site-packages/pandas/core/frame.py in apply(self, func, axis, raw, result_type, args, **kwds)
   6876             kwds=kwds,
   6877         )
-> 6878         return op.get_result()
   6879 
   6880     def applymap(self, func) -> "DataFrame":

~/PycharmProjects/MLProject/venv/lib/python3.7/site-packages/pandas/core/apply.py in get_result(self)
    184             return self.apply_raw()
    185 
--> 186         return self.apply_standard()
    187 
    188     def apply_empty_result(self):

~/PycharmProjects/MLProject/venv/lib/python3.7/site-packages/pandas/core/apply.py in apply_standard(self)
    311 
    312         # compute the result using the series generator
--> 313         results, res_index = self.apply_series_generator()
    314 
    315         # wrap results

~/PycharmProjects/MLProject/venv/lib/python3.7/site-packages/pandas/core/apply.py in apply_series_generator(self)
    339         else:
    340             for i, v in enumerate(series_gen):
--> 341                 results[i] = self.f(v)
    342                 keys.append(v.name)
    343 

<ipython-input-9-b391941204c4> in <lambda>(x)
     10            ['ProductRelated', 'ProductRelated_Duration']]    
     11 
---> 12 X['AvgAdministrative'] = X.apply(lambda x: AvgMinutes(Count = x['Administrative'], Duration = x['Administrative_Duration']), axis = 1)
     13 

<ipython-input-9-b391941204c4> in AvgMinutes(Count, Duration)
      3         output = 0
      4     elif Duration != 0:
----> 5         output = float(Duration)/float(Count)
      6     return output
      7 

ZeroDivisionError: float division by zero

**Comment by MartinBeckUT** [comment]
If using the original dataset without modifying it beforehand you shouldn't have any problem. The AvgMinutes function already checks for 0 values in Duration and sets output to 0.

The only reason this ZeroDivisionError should come up is if there were any rows that had 0 values in 'Administrative' and had values > 1 in the 'Administrative_Duration' column. However, I filtered through the original dataset following the code in the order of my posted jupyter notebook and noticed there were no rows that had 0 values 'Administrative' and values > 1 in 'Administrative_Duration'.
